# -*- coding: utf-8 -*-
"""marketbasket.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rkfd5AKd5SfXjbdBWiRiongcU7exPNP8
"""

pip install mlxtend

from mlxtend.preprocessing import TransactionEncoder

from mlxtend.frequent_patterns import apriori, association_rules

import pandas as pd

df = pd.read_csv('orders.csv')

dff = pd.read_csv('orderss.csv')

dff.head()

transaction_list = dff.groupby('SN')['PROD'].apply(list).tolist()

te = TransactionEncoder()
te_ary = te.fit(transaction_list).transform(transaction_list)
df_encoded = pd.DataFrame(te_ary, columns=te.columns_)

df_encoded.info

frequent_itemsets = apriori(df_encoded, min_support=0.04, use_colnames=True)

rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2)

rules

